# Generated by Django 5.1.6 on 2025-03-03 02:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_conta', models.CharField(max_length=20, unique=True, verbose_name='Número da Conta')),
                ('agencia', models.CharField(max_length=10, verbose_name='Agência')),
                ('tipo_conta', models.CharField(choices=[('CC', 'Conta Corrente'), ('CP', 'Conta Poupança'), ('CS', 'Conta Salário')], max_length=2, verbose_name='Tipo de Conta')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo')),
                ('ativa', models.BooleanField(default=True, verbose_name='Conta Ativa')),
                ('data_abertura', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Abertura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='servicos.cliente')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Solicitado')),
                ('valor_aprovado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Aprovado')),
                ('taxa_juros', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxa de Juros (% ao mês)')),
                ('prazo_meses', models.PositiveIntegerField(verbose_name='Prazo (meses)')),
                ('data_solicitacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Solicitação')),
                ('data_aprovacao', models.DateField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('SOL', 'Solicitado'), ('APR', 'Aprovado'), ('NEG', 'Negado'), ('PAG', 'Pago'), ('ATR', 'Atrasado')], default='SOL', max_length=3, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='servicos.cliente')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CDB', 'CDB'), ('LCI', 'LCI'), ('LCA', 'LCA'), ('FUN', 'Fundos'), ('ACO', 'Ações')], max_length=3, verbose_name='Tipo de Investimento')),
                ('valor_aplicado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Aplicado')),
                ('rentabilidade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rentabilidade (% ao ano)')),
                ('data_aplicacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Aplicação')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Investimento Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investimentos', to='servicos.cliente')),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id_transacao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('DEP', 'Depósito'), ('SAQ', 'Saque'), ('TRA', 'Transferência'), ('PAG', 'Pagamento')], max_length=3, verbose_name='Tipo de Transação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('PEN', 'Pendente'), ('CON', 'Confirmada'), ('CAN', 'Cancelada'), ('REJ', 'Rejeitada')], default='PEN', max_length=3, verbose_name='Status')),
                ('data_transacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Transação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_destino', to='servicos.contabancaria')),
                ('conta_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_origem', to='servicos.contabancaria')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-data_transacao'],
            },
        ),
    ]
